title: My Developer CV
author: fededev01
description: > # this means to ignore newlines until "baseurl:"
  With this GitHub page I'll introduce myself and my developer's skills
theme: jekyll-theme-midnight
google_analytics: UA-164005640-1
markdown: kramdown

# social links
twitter_username: fededev01 # DO NOT include the @ character, or else the build will fail!
github_username:  fededev01 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
